In [1]:

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [3]:
%pip install mlxtend

Defaulting to user installation because normal site-packages is not writeable
Collecting mlxtend
  Downloading mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: scipy>=1.16.3 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.16.3)
Requirement already satisfied: numpy>=2.3.5 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (2.3.5)
Requirement already satisfied: pandas>=2.3.3 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (2.3.3)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: joblib>=1.5.2 in c:\programdata\anaconda3\lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)
Requirement already satisfied: pillow>=9 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)
Downloading mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 538.0 kB/s eta 0:00:02
   --------------- ------------------------ 0.5/1.4 MB 538.0 kB/s eta 0:00:02
   --------------- ------------------------ 0.5/1.4 MB 538.0 kB/s eta 0:00:02
   --------------- ------------------------ 0.5/1.4 MB 538.0 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 442.7 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 442.7 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 442.7 kB/s eta 0:00:02
   ----------------------- ---------------- 0.8/1.4 MB 442.7 kB/s eta 0:00:02
   ------------------------------ --------- 1.0/1.4 MB 398.9 kB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 398.9 kB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 398.9 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 390.1 kB/s  0:00:03
Downloading matplotlib-3.11.0-cp313-cp313-win_amd64.whl (9.3 MB)
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.3 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.3 MB 311.6 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/9.3 MB 311.6 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/9.3 MB 311.6 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/9.3 MB 311.6 kB/s eta 0:00:29
   -- ------------------------------------- 0.5/9.3 MB 311.6 kB/s eta 0:00:29
   --- ------------------------------------ 0.8/9.3 MB 289.3 kB/s eta 0:00:30
   --- ------------------------------------ 0.8/9.3 MB 289.3 kB/s eta 0:00:30
   --- ------------------------------------ 0.8/9.3 MB 289.3 kB/s eta 0:00:30
   --- ------------------------------------ 0.8/9.3 MB 289.3 kB/s eta 0:00:30
   ---- ----------------------------------- 1.0/9.3 MB 284.1 kB/s eta 0:00:30
   ---- ----------------------------------- 1.0/9.3 MB 284.1 kB/s eta 0:00:30
   ---- ----------------------------------- 1.0/9.3 MB 284.1 kB/s eta 0:00:30
   ---- ----------------------------------- 1.0/9.3 MB 284.1 kB/s eta 0:00:30
   ---- ----------------------------------- 1.0/9.3 MB 284.1 kB/s eta 0:00:30
   ----- ---------------------------------- 1.3/9.3 MB 275.1 kB/s eta 0:00:30
   ----- ---------------------------------- 1.3/9.3 MB 275.1 kB/s eta 0:00:30
   ----- ---------------------------------- 1.3/9.3 MB 275.1 kB/s eta 0:00:30
   ----- ---------------------------------- 1.3/9.3 MB 275.1 kB/s eta 0:00:30
   ----- ---------------------------------- 1.3/9.3 MB 275.1 kB/s eta 0:00:30
   ------ --------------------------------- 1.6/9.3 MB 271.1 kB/s eta 0:00:29
   ------ --------------------------------- 1.6/9.3 MB 271.1 kB/s eta 0:00:29
   ------ --------------------------------- 1.6/9.3 MB 271.1 kB/s eta 0:00:29
   ------ --------------------------------- 1.6/9.3 MB 271.1 kB/s eta 0:00:29
   ------ --------------------------------- 1.6/9.3 MB 271.1 kB/s eta 0:00:29
   ------- -------------------------------- 1.8/9.3 MB 274.5 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.3 MB 274.5 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.3 MB 274.5 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.3 MB 274.5 kB/s eta 0:00:28
   ------- -------------------------------- 1.8/9.3 MB 274.5 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.3 MB 265.2 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.3 MB 265.2 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.3 MB 265.2 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.3 MB 265.2 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.3 MB 265.2 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.3 MB 265.2 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.3 MB 265.2 kB/s eta 0:00:28
   -------- ------------------------------- 2.1/9.3 MB 265.2 kB/s eta 0:00:28
   ---------- ----------------------------- 2.4/9.3 MB 247.2 kB/s eta 0:00:29
   ---------- ----------------------------- 2.4/9.3 MB 247.2 kB/s eta 0:00:29
   ---------- ----------------------------- 2.4/9.3 MB 247.2 kB/s eta 0:00:29
   ---------- ----------------------------- 2.4/9.3 MB 247.2 kB/s eta 0:00:29
   ---------- ----------------------------- 2.4/9.3 MB 247.2 kB/s eta 0:00:29
   ---------- ----------------------------- 2.4/9.3 MB 247.2 kB/s eta 0:00:29
   ---------- ----------------------------- 2.4/9.3 MB 247.2 kB/s eta 0:00:29
   ---------- ----------------------------- 2.4/9.3 MB 247.2 kB/s eta 0:00:29
   ----------- ---------------------------- 2.6/9.3 MB 229.7 kB/s eta 0:00:30
   ----------- ---------------------------- 2.6/9.3 MB 229.7 kB/s eta 0:00:30
   ----------- ---------------------------- 2.6/9.3 MB 229.7 kB/s eta 0:00:30
   ----------- ---------------------------- 2.6/9.3 MB 229.7 kB/s eta 0:00:30
   ----------- ---------------------------- 2.6/9.3 MB 229.7 kB/s eta 0:00:30
   ----------- ---------------------------- 2.6/9.3 MB 229.7 kB/s eta 0:00:30
   ----------- ---------------------------- 2.6/9.3 MB 229.7 kB/s eta 0:00:30
   ------------ --------------------------- 2.9/9.3 MB 226.0 kB/s eta 0:00:29
   ------------ --------------------------- 2.9/9.3 MB 226.0 kB/s eta 0:00:29
   ------------ --------------------------- 2.9/9.3 MB 226.0 kB/s eta 0:00:29
   ------------ --------------------------- 2.9/9.3 MB 226.0 kB/s eta 0:00:29
   ------------ --------------------------- 2.9/9.3 MB 226.0 kB/s eta 0:00:29
   ------------ --------------------------- 2.9/9.3 MB 226.0 kB/s eta 0:00:29
   ------------ --------------------------- 2.9/9.3 MB 226.0 kB/s eta 0:00:29
   ------------- -------------------------- 3.1/9.3 MB 218.6 kB/s eta 0:00:29
   ------------- -------------------------- 3.1/9.3 MB 218.6 kB/s eta 0:00:29
   ------------- -------------------------- 3.1/9.3 MB 218.6 kB/s eta 0:00:29
   ------------- -------------------------- 3.1/9.3 MB 218.6 kB/s eta 0:00:29
   ------------- -------------------------- 3.1/9.3 MB 218.6 kB/s eta 0:00:29
   ------------- -------------------------- 3.1/9.3 MB 218.6 kB/s eta 0:00:29
   ------------- -------------------------- 3.1/9.3 MB 218.6 kB/s eta 0:00:29
   ------------- -------------------------- 3.1/9.3 MB 218.6 kB/s eta 0:00:29
   -------------- ------------------------- 3.4/9.3 MB 213.5 kB/s eta 0:00:28
   -------------- ------------------------- 3.4/9.3 MB 213.5 kB/s eta 0:00:28
   -------------- ------------------------- 3.4/9.3 MB 213.5 kB/s eta 0:00:28
   -------------- ------------------------- 3.4/9.3 MB 213.5 kB/s eta 0:00:28
   -------------- ------------------------- 3.4/9.3 MB 213.5 kB/s eta 0:00:28
   -------------- ------------------------- 3.4/9.3 MB 213.5 kB/s eta 0:00:28
   -------------- ------------------------- 3.4/9.3 MB 213.5 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   --------------- ------------------------ 3.7/9.3 MB 209.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ---------------- ----------------------- 3.9/9.3 MB 197.4 kB/s eta 0:00:28
   ----------------- ---------------------- 4.2/9.3 MB 186.5 kB/s eta 0:00:28
   ----------------- ---------------------- 4.2/9.3 MB 186.5 kB/s eta 0:00:28
   ----------------- ---------------------- 4.2/9.3 MB 186.5 kB/s eta 0:00:28
   ----------------- ---------------------- 4.2/9.3 MB 186.5 kB/s eta 0:00:28
   ----------------- ---------------------- 4.2/9.3 MB 186.5 kB/s eta 0:00:28
   ----------------- ---------------------- 4.2/9.3 MB 186.5 kB/s eta 0:00:28
   ----------------- ---------------------- 4.2/9.3 MB 186.5 kB/s eta 0:00:28
   ----------------- ---------------------- 4.2/9.3 MB 186.5 kB/s eta 0:00:28
   ------------------- -------------------- 4.5/9.3 MB 184.3 kB/s eta 0:00:27
   ------------------- -------------------- 4.5/9.3 MB 184.3 kB/s eta 0:00:27
   ------------------- -------------------- 4.5/9.3 MB 184.3 kB/s eta 0:00:27
   ------------------- -------------------- 4.5/9.3 MB 184.3 kB/s eta 0:00:27
   ------------------- -------------------- 4.5/9.3 MB 184.3 kB/s eta 0:00:27
   ------------------- -------------------- 4.5/9.3 MB 184.3 kB/s eta 0:00:27
   ------------------- -------------------- 4.5/9.3 MB 184.3 kB/s eta 0:00:27
   ------------------- -------------------- 4.5/9.3 MB 184.3 kB/s eta 0:00:27
   ------------------- -------------------- 4.5/9.3 MB 184.3 kB/s eta 0:00:27
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   -------------------- ------------------- 4.7/9.3 MB 180.2 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   --------------------- ------------------ 5.0/9.3 MB 172.7 kB/s eta 0:00:26
   ---------------------- ----------------- 5.2/9.3 MB 161.6 kB/s eta 0:00:26
   ---------------------- ----------------- 5.2/9.3 MB 161.6 kB/s eta 0:00:26
   ---------------------- ----------------- 5.2/9.3 MB 161.6 kB/s eta 0:00:26
   ---------------------- ----------------- 5.2/9.3 MB 161.6 kB/s eta 0:00:26
   ---------------------- ----------------- 5.2/9.3 MB 161.6 kB/s eta 0:00:26
   ---------------------- ----------------- 5.2/9.3 MB 161.6 kB/s eta 0:00:26
   ---------------------- ----------------- 5.2/9.3 MB 161.6 kB/s eta 0:00:26
   ---------------------- ----------------- 5.2/9.3 MB 161.6 kB/s eta 0:00:26
   ----------------------- ---------------- 5.5/9.3 MB 158.2 kB/s eta 0:00:25
   ----------------------- ---------------- 5.5/9.3 MB 158.2 kB/s eta 0:00:25
   ----------------------- ---------------- 5.5/9.3 MB 158.2 kB/s eta 0:00:25
   ----------------------- ---------------- 5.5/9.3 MB 158.2 kB/s eta 0:00:25
   ----------------------- ---------------- 5.5/9.3 MB 158.2 kB/s eta 0:00:25
   ----------------------- ---------------- 5.5/9.3 MB 158.2 kB/s eta 0:00:25
   ----------------------- ---------------- 5.5/9.3 MB 158.2 kB/s eta 0:00:25
   ----------------------- ---------------- 5.5/9.3 MB 158.2 kB/s eta 0:00:25
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------ --------------- 5.8/9.3 MB 150.6 kB/s eta 0:00:24
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   ------------------------- -------------- 6.0/9.3 MB 133.3 kB/s eta 0:00:25
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   -------------------------- ------------- 6.3/9.3 MB 128.2 kB/s eta 0:00:24
   ---------------------------- ----------- 6.6/9.3 MB 125.4 kB/s eta 0:00:23
   ---------------------------- ----------- 6.6/9.3 MB 125.4 kB/s eta 0:00:23
   ---------------------------- ----------- 6.6/9.3 MB 125.4 kB/s eta 0:00:23
   ---------------------------- ----------- 6.6/9.3 MB 125.4 kB/s eta 0:00:23
   ---------------------------- ----------- 6.6/9.3 MB 125.4 kB/s eta 0:00:23
   ---------------------------- ----------- 6.6/9.3 MB 125.4 kB/s eta 0:00:23

In [4]:
import pandas as pd
import numpy as np
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv(r'C:\EXL\basket.csv')
df.head()

,0,1,2,3,4,5,6,7,8,9,10
0,whole milk,pastry,salty snack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sausage,whole milk,semi-finished bread,yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,soda,pickled vegetables,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,canned beer,misc. beverages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,sausage,hygiene articles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.fillna('!',inplace=True)
trans = df.values.tolist()

In [7]:
for i in range(len(trans)):
    trans[i] = [x for x in trans[i] if not x=='!']

In [8]:
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_ary = te.fit(trans).transform(trans)
transactions = pd.DataFrame(te_ary, columns=te.columns_)

In [9]:
freq_items = apriori(transactions, min_support=0.001, use_colnames=True, verbose=1)
freq_items.head(7)

Processing 4 combinations | Sampling itemset size 4e 32

    support                 itemsets
0  0.004010  (Instant food products)
1  0.021386               (UHT-milk)
2  0.001470       (abrasive cleaner)
3  0.001938       (artif. sweetener)
4  0.008087          (baking powder)
5  0.001136       (bathroom cleaner)
6  0.033950                   (beef)

In [10]:
freq_items['length'] = freq_items['itemsets'].apply(lambda x: len(x))

In [11]:
freq_items.sort_values('length',ascending=False)

      support                                    itemsets  length
749  0.001470               (yogurt, sausage, whole milk)       3
745  0.001136           (sausage, rolls/buns, whole milk)       3
742  0.001203  (rolls/buns, other vegetables, whole milk)       3
743  0.001136        (other vegetables, soda, whole milk)       3
744  0.001136      (yogurt, other vegetables, whole milk)       3
..        ...                                         ...     ...
100  0.007819                                (pot plants)       1
99   0.037091                                      (pork)       1
98   0.003208                                   (popcorn)       1
97   0.049054                                 (pip fruit)       1
0    0.004010                     (Instant food products)       1

[750 rows x 3 columns]

In [12]:
rules = association_rules(freq_items, metric="confidence", min_threshold=0.001)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(bottled water),(UHT-milk),0.060683,0.021386,0.001069,0.017621,0.823954,1.0,-0.000228,0.996168,-0.185312,0.013201,-0.003847,0.033811
1,(UHT-milk),(bottled water),0.021386,0.060683,0.001069,0.050000,0.823954,1.0,-0.000228,0.988755,-0.179204,0.013201,-0.011373,0.033811
2,(other vegetables),(UHT-milk),0.122101,0.021386,0.002139,0.017515,0.818993,1.0,-0.000473,0.996060,-0.201119,0.015130,-0.003956,0.058758
3,(UHT-milk),(other vegetables),0.021386,0.122101,0.002139,0.100000,0.818993,1.0,-0.000473,0.975443,-0.184234,0.015130,-0.025175,0.058758
4,(rolls/buns),(UHT-milk),0.110005,0.021386,0.001804,0.016403,0.767013,1.0,-0.000548,0.994934,-0.254457,0.013925,-0.005092,0.050389

In [13]:
rules.sort_values('confidence', ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
1232,"(yogurt, sausage)",(whole milk),0.005748,0.157923,0.001470,0.255814,1.619866,1.0,0.000563,1.131541,0.384877,0.009065,0.116250,0.132562
1208,"(sausage, rolls/buns)",(whole milk),0.005347,0.157923,0.001136,0.212500,1.345594,1.0,0.000292,1.069304,0.258214,0.007007,0.064813,0.109847
1226,"(sausage, soda)",(whole milk),0.005948,0.157923,0.001069,0.179775,1.138374,1.0,0.000130,1.026642,0.122281,0.006568,0.025951,0.093273
1108,(semi-finished bread),(whole milk),0.009490,0.157923,0.001671,0.176056,1.114825,1.0,0.000172,1.022008,0.103985,0.010081,0.021534,0.093318
1220,"(yogurt, rolls/buns)",(whole milk),0.007819,0.157923,0.001337,0.170940,1.082428,1.0,0.000102,1.015701,0.076751,0.008130,0.015459,0.089702
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1231,(whole milk),"(sausage, soda)",0.157923,0.005948,0.001069,0.006771,1.138374,1.0,0.000130,1.000829,0.144350,0.006568,0.000828,0.093273
959,(whole milk),(pasta),0.157923,0.008087,0.001069,0.006771,0.837316,1.0,-0.000208,0.998675,-0.187474,0.006483,-0.001326,0.069501
1219,(whole milk),"(rolls/buns, soda)",0.157923,0.008087,0.001002,0.006348,0.784984,1.0,-0.000275,0.998250,-0.245443,0.006075,-0.001753,0.065157
983,(whole milk),(pickled vegetables),0.157923,0.008955,0.001002,0.006348,0.708829,1.0,-0.000412,0.997376,-0.327873,0.006044,-0.002631,0.059144
1021,(whole milk),(pot plants),0.157923,0.007819,0.001002,0.006348,0.811821,1.0,-0.000232,0.998519,-0.215852,0.006085,-0.001483,0.067276